export const DATA_NHAN_KHAU_HOC = [
  {
    id: 1,
    name: 'Địa bàn',
    behaviorType: 1,
    behaviorName: 'Nhân khẩu học',
    groupCode: null,
    groupName: null,
    optionProperty: 'address',
    optionType: null,
    optionCompare: null,
    optionValue: null,
    refGroup: null,
    criteriaType: null,
    type: 'address',
    status: 1,
    customerType: 3,
    referenceData: null,
  },
  {
    id: 2,
    name: 'Độ tuổi',
    behaviorType: 1,
    behaviorName: 'Nhân khẩu học',
    groupCode: null,
    groupName: null,
    optionProperty: 'age',
    optionType: 3,
    optionCompare: null,
    optionValue:
      '[{"key":"< 25 tuổi", "type_compare": 3, "value":["25"]}, \n{"key": "25-35", "type_compare": 5,"value":["25", "35"]},\n{"key": "35-45", "type_compare": 5,"value":["35", "45"]},\n{"key": "45-55", "type_compare": 5,"value":["45", "55"]},\n{"key": "> 55 tuổi", "type_compare": 1,"value":["55", "999"]},\n{"key": "Chưa xác định", "value":null}]',
    refGroup: null,
    criteriaType: null,
    type: 'profile',
    status: 1,
    customerType: 3,
    referenceData: null,
  },
  {
    id: 3,
    name: 'Giới tính',
    behaviorType: 1,
    behaviorName: 'Nhân khẩu học',
    groupCode: null,
    groupName: null,
    optionProperty: 'gender',
    optionType: 3,
    optionCompare: null,
    optionValue: '[{"key":"Nam", "value":["male"]}, \n{"key": "Nữ", "value":["female"]},\n{"key": "Khác", "value":["other"]}]',
    refGroup: null,
    criteriaType: null,
    type: 'profile',
    status: 1,
    customerType: 3,
    referenceData: null,
  },
  {
    id: 4,
    name: 'Thu nhập',
    behaviorType: 1,
    behaviorName: 'Nhân khẩu học',
    groupCode: null,
    groupName: null,
    optionProperty: 'salary',
    optionType: 3,
    optionCompare: null,
    optionValue:
      '[{"key":"Dưới 10", "type_compare": 3,"value":["0", "10000000"]}, \n{"key": "10-25", "type_compare": 5, "value":["10000000", "25000000"]},\n{"key": "25-40", "type_compare": 5,"value":["25000000", "40000000"]},\n{"key": "Trên 40", "type_compare": 1,"value":["40000000"]}]',
    refGroup: null,
    criteriaType: null,
    type: 'profile',
    status: 1,
    customerType: 3,
    referenceData: null,
  },
  {
    id: 5,
    name: 'Ngành nghề',
    behaviorType: 1,
    behaviorName: 'Nhân khẩu học',
    groupCode: null,
    groupName: null,
    optionProperty: 'job',
    optionType: 3,
    optionCompare: null,
    optionValue:
      '[{"key":"Văn phòng", "value":["1"]}, \n{"key": "Học sinh/sinh viên", "value":["2"]},\n{"key": "Công nhân", "value":["3"]},\n{"key": "Lao động tự do", "value":["4"]},\n{"key": "Tiểu thương", "value":["5"]},\n{"key": "Thương gia", "value":"6"},\n{"key": "Khác", "value":"7"}\n]',
    refGroup: null,
    criteriaType: null,
    type: 'profile',
    status: 1,
    customerType: 3,
    referenceData: null,
  },
  {
    id: 27,
    name: 'Đang sử dụng gói tích hợp',
    behaviorType: 3,
    behaviorName: 'Hành vi sử dụng',
    groupCode: null,
    groupName: null,
    optionProperty: null,
    optionType: 4,
    optionCompare: null,
    optionValue: null,
    refGroup: null,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 3,
    referenceData: null,
  },
  {
    id: 28,
    name: 'Nhà mạng internet',
    behaviorType: 3,
    behaviorName: 'Hành vi sử dụng',
    groupCode: null,
    groupName: null,
    optionProperty: null,
    optionType: 3,
    optionCompare: null,
    optionValue: '[{"key":"FPT", "value":["FPT"]}, \n{"key": "VIETTEL", "value":["VIETTEL"]}]',
    refGroup: null,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 3,
    referenceData: null,
  },
  {
    id: 29,
    name: 'Truyền hình',
    behaviorType: 3,
    behaviorName: 'Hành vi sử dụng',
    groupCode: null,
    groupName: null,
    optionProperty: null,
    optionType: 3,
    optionCompare: null,
    optionValue:
      '[{"key":"SCTV Cap", "value":["SCTV Cap"]}, \n{"key":"Vieon", "value":["Vieon"]}, \n{"key":"NETFLIX", "value":["NETFLIX"]}, \n{"key":"VTV Cap", "value":["VTV Cap"]}, \n{"key":"FPT Telecom", "value":["FPT Telecom"]}, \n{"key":"HTVC", "value":["HTVC"]}, \n{"key":"Viettel Telecom", "value":["Viettel Telecom"]}, \n{"key":"VTC", "value":["VTC"]}, \n{"key": "An Viên", "value":["An Viên"]}]',
    refGroup: null,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 3,
    referenceData: null,
  },
  {
    id: 30,
    name: 'Đóng trước cước Internet nhà mạng khác',
    behaviorType: 3,
    behaviorName: 'Hành vi sử dụng',
    groupCode: null,
    groupName: null,
    optionProperty: null,
    optionType: 4,
    optionCompare: null,
    optionValue: null,
    refGroup: null,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 3,
    referenceData: null,
  },
  {
    id: 31,
    name: 'Đóng trước cước truyền hình nhà mạng khác',
    behaviorType: 3,
    behaviorName: 'Hành vi sử dụng',
    groupCode: null,
    groupName: null,
    optionProperty: null,
    optionType: 4,
    optionCompare: null,
    optionValue: null,
    refGroup: null,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 3,
    referenceData: null,
  },
  {
    id: 32,
    name: 'Số tháng sẽ hết hạn đóng trước cước nhà mạng khác',
    behaviorType: 3,
    behaviorName: 'Hành vi sử dụng',
    groupCode: null,
    groupName: null,
    optionProperty: null,
    optionType: 3,
    optionCompare: null,
    optionValue: '[{"key":"T", "value":["T"]}, \n{"key":"T+1", "value":["T+1"]}, \n{"key":"T+2", "value":["T+2"]}]',
    refGroup: null,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 3,
    referenceData: null,
  },
  {
    id: 33,
    name: 'KH sử dụng Smart TV',
    behaviorType: 3,
    behaviorName: 'Hành vi sử dụng',
    groupCode: null,
    groupName: null,
    optionProperty: null,
    optionType: 4,
    optionCompare: null,
    optionValue: null,
    refGroup: null,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 3,
    referenceData: null,
  },
  {
    id: 34,
    name: 'Khách hàng đang dùng FPT sắp hết hạn cam kết',
    behaviorType: 3,
    behaviorName: 'Hành vi sử dụng',
    groupCode: null,
    groupName: null,
    optionProperty: null,
    optionType: 4,
    optionCompare: null,
    optionValue: null,
    refGroup: null,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 3,
    referenceData: null,
  },
  {
    id: 35,
    name: 'Khách hàng đang dùng FPT sắp hết hạn cam kết',
    behaviorType: 3,
    behaviorName: 'Hành vi sử dụng',
    groupCode: null,
    groupName: null,
    optionProperty: null,
    optionType: 4,
    optionCompare: null,
    optionValue: null,
    refGroup: null,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 3,
    referenceData: null,
  },
  {
    id: 36,
    name: 'Đang sắp hết hạn đóng trước cước tháng ',
    behaviorType: 3,
    behaviorName: 'Hành vi sử dụng',
    groupCode: null,
    groupName: null,
    optionProperty: null,
    optionType: 4,
    optionCompare: null,
    optionValue: '[{"key":"T", "value":["T"]}, \n{"key":"T+1", "value":["T+1"]}, \n{"key":"T+2", "value":["T+2"]}]',
    refGroup: null,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 3,
    referenceData: null,
  },
  {
    id: 37,
    name: 'Cước hàng tháng nhà mạng khác',
    behaviorType: 3,
    behaviorName: 'Hành vi sử dụng',
    groupCode: null,
    groupName: null,
    optionProperty: null,
    optionType: 1,
    optionCompare: '0,5,2,4',
    optionValue: null,
    refGroup: null,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 3,
    referenceData: null,
  },
  {
    id: 38,
    name: 'Đặt cọc',
    behaviorType: 3,
    behaviorName: 'Hành vi sử dụng',
    groupCode: null,
    groupName: null,
    optionProperty: null,
    optionType: 5,
    optionCompare: null,
    optionValue: null,
    refGroup: null,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 3,
    referenceData: null,
  },
  {
    id: 39,
    name: 'Đánh giá chất lượng dịch vụ',
    behaviorType: 3,
    behaviorName: 'Hành vi sử dụng',
    groupCode: null,
    groupName: null,
    optionProperty: null,
    optionType: 3,
    optionCompare: null,
    optionValue: '[{"key":"Tốt", "value":["Tốt"]}, \n{"key":"Khá tốt", "value":["Khá tốt"]}, \n{"key":"Bình thường", "value":["Bình thường"]},\n{"key":"Kém", "value":["Kém"]},\n{"key":"Rất kém", "value":["Rất kém"]}]',
    refGroup: null,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 3,
    referenceData: null,
  },
  {
    id: 8,
    name: 'Băng rộng cố định',
    behaviorType: 2,
    behaviorName: 'Nhu cầu dịch vụ mới',
    groupCode: null,
    groupName: null,
    optionProperty: 'BRCD',
    optionType: 3,
    optionCompare: null,
    optionValue: null,
    refGroup: 3,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 1,
    referenceData: [],
  },
  {
    id: 6,
    name: 'Cố định',
    behaviorType: 2,
    behaviorName: 'Nhu cầu dịch vụ mới',
    groupCode: null,
    groupName: null,
    optionProperty: 'CD',
    optionType: 3,
    optionCompare: null,
    optionValue: null,
    refGroup: 1,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 1,
    referenceData: [
      {
        id: 363,
        externalId: '1',
        name: 'Điện thoại cố định',
        externalCode: 'CD',
        refGroup: '1',
      },
      {
        id: 364,
        externalId: '2',
        name: 'Máy FAX',
        externalCode: 'CD',
        refGroup: '1',
      },
      {
        id: 365,
        externalId: '3',
        name: 'Trung kế thường',
        externalCode: 'CD',
        refGroup: '1',
      },
      {
        id: 366,
        externalId: '4',
        name: 'Trung kế tương tự',
        externalCode: 'CD',
        refGroup: '1',
      },
      {
        id: 367,
        externalId: '5',
        name: 'Trung kế 2M',
        externalCode: 'CD',
        refGroup: '1',
      },
      {
        id: 368,
        externalId: '6',
        name: 'Tổng đài',
        externalCode: 'CD',
        refGroup: '1',
      },
      {
        id: 369,
        externalId: '7',
        name: 'Điện thoại thẻ',
        externalCode: 'CD',
        refGroup: '1',
      },
      {
        id: 370,
        externalId: '8',
        name: 'VPabx',
        externalCode: 'CD',
        refGroup: '1',
      },
      {
        id: 371,
        externalId: '14',
        name: 'ISDN 2B+D cáp quang',
        externalCode: 'CD',
        refGroup: '1',
      },
      {
        id: 372,
        externalId: '15',
        name: 'ISDN 30B+D cáp đồng',
        externalCode: 'CD',
        refGroup: '1',
      },
      {
        id: 373,
        externalId: '16',
        name: 'ISDN 2B+D cáp đồng',
        externalCode: 'CD',
        refGroup: '1',
      },
      {
        id: 374,
        externalId: '17',
        name: 'ISDN 30B+D cáp quang',
        externalCode: 'CD',
        refGroup: '1',
      },
      {
        id: 375,
        externalId: '36',
        name: 'Cố định tỉnh khác',
        externalCode: 'CD',
        refGroup: '1',
      },
      {
        id: 376,
        externalId: '60',
        name: 'Centrex',
        externalCode: 'CD',
        refGroup: '1',
      },
      {
        id: 377,
        externalId: '108',
        name: 'Điện thoại vô tuyến',
        externalCode: 'CD',
        refGroup: '1',
      },
    ],
  },
  {
    id: 15,
    name: 'Camera / MegaEyes',
    behaviorType: 2,
    behaviorName: 'Nhu cầu dịch vụ mới',
    groupCode: null,
    groupName: null,
    optionProperty: 'MEGAEYES',
    optionType: 3,
    optionCompare: null,
    optionValue: null,
    refGroup: 12,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 1,
    referenceData: [
      {
        id: 493,
        externalId: '84',
        name: 'Camera An Ninh',
        externalCode: 'MEGAEYES',
        refGroup: '12',
      },
      {
        id: 494,
        externalId: '31',
        name: 'VNPT Camera',
        externalCode: 'MEGAEYES',
        refGroup: '12',
      },
      {
        id: 495,
        externalId: '37',
        name: 'IP Camera',
        externalCode: 'MEGAEYES',
        refGroup: '12',
      },
      {
        id: 496,
        externalId: '70',
        name: 'Camera học đường',
        externalCode: 'MEGAEYES',
        refGroup: '12',
      },
      {
        id: 497,
        externalId: '83',
        name: 'Cloud Camera',
        externalCode: 'MEGAEYES',
        refGroup: '12',
      },
      {
        id: 498,
        externalId: '222',
        name: 'Indoor Camera PT',
        externalCode: 'MEGAEYES',
        refGroup: '12',
      },
      {
        id: 499,
        externalId: '224',
        name: 'Outdoor Camera PT',
        externalCode: 'MEGAEYES',
        refGroup: '12',
      },
      {
        id: 500,
        externalId: '588',
        name: 'Home Cloud camera',
        externalCode: 'MEGAEYES',
        refGroup: '12',
      },
    ],
  },
  {
    id: 14,
    name: 'IMS',
    behaviorType: 2,
    behaviorName: 'Nhu cầu dịch vụ mới',
    groupCode: null,
    groupName: null,
    optionProperty: 'IMS',
    optionType: 3,
    optionCompare: null,
    optionValue: null,
    refGroup: 11,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 1,
    referenceData: [
      {
        id: 488,
        externalId: '109',
        name: 'B-FONE',
        externalCode: 'IMS',
        refGroup: '11',
      },
      {
        id: 489,
        externalId: '62',
        name: 'Thuê bao POTS',
        externalCode: 'IMS',
        refGroup: '11',
      },
      {
        id: 490,
        externalId: '63',
        name: 'Thuê bao SIP',
        externalCode: 'IMS',
        refGroup: '11',
      },
      {
        id: 491,
        externalId: '64',
        name: 'Thuê bao RGW',
        externalCode: 'IMS',
        refGroup: '11',
      },
      {
        id: 492,
        externalId: '77',
        name: 'Thuê bao Sip Trunking',
        externalCode: 'IMS',
        refGroup: '11',
      },
    ],
  },
  {
    id: 11,
    name: 'MegaWan',
    behaviorType: 2,
    behaviorName: 'Nhu cầu dịch vụ mới',
    groupCode: null,
    groupName: null,
    optionProperty: 'WAN',
    optionType: 3,
    optionCompare: null,
    optionValue: null,
    refGroup: 8,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 1,
    referenceData: [
      {
        id: 416,
        externalId: '85',
        name: 'Kênh truyền dẫn VNP',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 417,
        externalId: '128',
        name: 'Sợi quang trắng',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 418,
        externalId: '133',
        name: 'KTR luồng - luồng',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 419,
        externalId: '23',
        name: 'Megawan ADSL',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 420,
        externalId: '25',
        name: 'Megawan SHDSL',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 421,
        externalId: '26',
        name: 'Megawan quang FE',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 422,
        externalId: '27',
        name: 'MetroNet FE',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 423,
        externalId: '28',
        name: 'MetroNet GE',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 424,
        externalId: '30',
        name: 'Megawan quang GE',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 425,
        externalId: '74',
        name: 'Megawan ADSL 2M',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 426,
        externalId: '75',
        name: 'MetroNet 2FE',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 427,
        externalId: '96',
        name: 'KTR-Leasedline GE',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 428,
        externalId: '98',
        name: 'KTR-Leasedline STM1',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 429,
        externalId: '99',
        name: 'KTR-Leasedline nx64k',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 430,
        externalId: '100',
        name: 'KTR-Trực thông đồng',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 431,
        externalId: '101',
        name: 'KTR-Trực thông quang',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 432,
        externalId: '102',
        name: 'KTR-Đôi cáp quang',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 433,
        externalId: '103',
        name: 'KTR-Đôi cáp đồng',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 434,
        externalId: '104',
        name: 'KTR-Leasedline FE',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 435,
        externalId: '105',
        name: 'KTR-Nail up',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 436,
        externalId: '107',
        name: 'Cáp quang trắng',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 437,
        externalId: '134',
        name: 'Internet trực tiếp',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 438,
        externalId: '138',
        name: 'MetroNet 10GE',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 439,
        externalId: '169',
        name: 'MetroNet XE',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 440,
        externalId: '135',
        name: 'Metronet SHDSL',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 441,
        externalId: '246',
        name: 'Megawan_POP',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 442,
        externalId: '247',
        name: 'Megawan_NNI',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 443,
        externalId: '259',
        name: 'IP Transit LL',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 444,
        externalId: '260',
        name: 'IP Port',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 445,
        externalId: '275',
        name: 'Megawan 10GE',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 446,
        externalId: '306',
        name: 'MegaWanIOT',
        externalCode: 'WAN',
        refGroup: '8',
      },
      {
        id: 447,
        externalId: '97',
        name: 'KTR-Leasedline E1',
        externalCode: 'WAN',
        refGroup: '8',
      },
    ],
  },
  {
    id: 7,
    name: 'Di động',
    behaviorType: 2,
    behaviorName: 'Nhu cầu dịch vụ mới',
    groupCode: null,
    groupName: null,
    optionProperty: 'DD',
    optionType: 3,
    optionCompare: null,
    optionValue: null,
    refGroup: 2,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 1,
    referenceData: [
      {
        id: 378,
        externalId: '2119',
        name: 'Hòa mạng chuyển tỉnh',
        externalCode: 'DD',
        refGroup: '2',
      },
      {
        id: 379,
        externalId: '20',
        name: 'Di động trả sau',
        externalCode: 'DD',
        refGroup: '2',
      },
      {
        id: 380,
        externalId: '21',
        name: 'Di động trả trước',
        externalCode: 'DD',
        refGroup: '2',
      },
      {
        id: 381,
        externalId: '2111',
        name: 'Di động trả sau (MNP)',
        externalCode: 'DD',
        refGroup: '2',
      },
      {
        id: 382,
        externalId: '2112',
        name: 'Trả trước chuyển trả sau',
        externalCode: 'DD',
        refGroup: '2',
      },
    ],
  },
  {
    id: 9,
    name: 'Email',
    behaviorType: 2,
    behaviorName: 'Nhu cầu dịch vụ mới',
    groupCode: null,
    groupName: null,
    optionProperty: 'Email',
    optionType: 3,
    optionCompare: null,
    optionValue: null,
    refGroup: 6,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 1,
    referenceData: [
      {
        id: 407,
        externalId: '13',
        name: 'Email',
        externalCode: 'EMAIL',
        refGroup: '6',
      },
      {
        id: 408,
        externalId: '125',
        name: 'VN mail',
        externalCode: 'EMAIL',
        refGroup: '6',
      },
    ],
  },
  {
    id: 17,
    name: 'An toàn bảo mật thông tin',
    behaviorType: 2,
    behaviorName: 'Nhu cầu dịch vụ mới',
    groupCode: null,
    groupName: null,
    optionProperty: 'BMTT',
    optionType: 3,
    optionCompare: null,
    optionValue: null,
    refGroup: 14,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 1,
    referenceData: [
      {
        id: 512,
        externalId: '24',
        name: 'F-secure',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 513,
        externalId: '55',
        name: 'CA-TAX',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 514,
        externalId: '78',
        name: 'VNPT SSL',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 515,
        externalId: '114',
        name: 'Mega Green',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 516,
        externalId: '115',
        name: 'Security',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 517,
        externalId: '116',
        name: 'VNPT CA',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 518,
        externalId: '117',
        name: 'CA-IVAN',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 519,
        externalId: '126',
        name: 'Antivirus',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 520,
        externalId: '132',
        name: 'VNPT BHXH',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 521,
        externalId: '154',
        name: 'VNPT TAX',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 522,
        externalId: '181',
        name: 'VNPT Ký số',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 523,
        externalId: '276',
        name: 'VNPT eKYC',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 524,
        externalId: '279',
        name: 'VNPT AntiDDoS',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 525,
        externalId: '288',
        name: 'VNPT SmartCA',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 526,
        externalId: '293',
        name: 'VNPT BioID',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 527,
        externalId: '297',
        name: 'VNPT MSS',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 528,
        externalId: '318',
        name: 'SmartCa PS',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 529,
        externalId: '324',
        name: 'VNPT Smart IR',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 530,
        externalId: '325',
        name: 'VNPT DNS Protection',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 531,
        externalId: '333',
        name: 'Mobile ID',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 532,
        externalId: '334',
        name: 'VNPT Pentest',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 533,
        externalId: '335',
        name: 'Đào tạo ATTT',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 534,
        externalId: '350',
        name: 'Tư vấn ATTT',
        externalCode: 'BMTT',
        refGroup: '14',
      },
      {
        id: 535,
        externalId: '2113',
        name: 'Bảo mật KAS',
        externalCode: 'BMTT',
        refGroup: '14',
      },
    ],
  },
  {
    id: 16,
    name: 'Hội nghị truyền hình',
    behaviorType: 2,
    behaviorName: 'Nhu cầu dịch vụ mới',
    groupCode: null,
    groupName: null,
    optionProperty: 'HNTH',
    optionType: 3,
    optionCompare: null,
    optionValue: null,
    refGroup: 13,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 1,
    referenceData: [
      {
        id: 501,
        externalId: '89',
        name: 'VNPT Meeting',
        externalCode: 'HNTH',
        refGroup: '13',
      },
      {
        id: 502,
        externalId: '90',
        name: 'Hội nghị truyền hình NGN',
        externalCode: 'HNTH',
        refGroup: '13',
      },
      {
        id: 503,
        externalId: '91',
        name: 'Mega Vmeeting HD',
        externalCode: 'HNTH',
        refGroup: '13',
      },
      {
        id: 504,
        externalId: '92',
        name: 'Mega Vmeeting Nội bộ',
        externalCode: 'HNTH',
        refGroup: '13',
      },
      {
        id: 505,
        externalId: '113',
        name: 'Mega Vmeeting SD',
        externalCode: 'HNTH',
        refGroup: '13',
      },
      {
        id: 506,
        externalId: '146',
        name: 'Truyền dẫn tín hiệu truyền hình',
        externalCode: 'HNTH',
        refGroup: '13',
      },
      {
        id: 507,
        externalId: '311',
        name: 'Thu phát hình quốc tế',
        externalCode: 'HNTH',
        refGroup: '13',
      },
      {
        id: 508,
        externalId: '312',
        name: 'Cho thuê băng tần vệ tinh',
        externalCode: 'HNTH',
        refGroup: '13',
      },
      {
        id: 509,
        externalId: '313',
        name: 'Uplink',
        externalCode: 'HNTH',
        refGroup: '13',
      },
      {
        id: 510,
        externalId: '314',
        name: 'VSAT-IP',
        externalCode: 'HNTH',
        refGroup: '13',
      },
      {
        id: 511,
        externalId: '315',
        name: 'VSAT-PAMA',
        externalCode: 'HNTH',
        refGroup: '13',
      },
    ],
  },
  {
    id: 10,
    name: 'Metronet',
    behaviorType: 2,
    behaviorName: 'Nhu cầu dịch vụ mới',
    groupCode: null,
    groupName: null,
    optionProperty: 'MTN',
    optionType: 3,
    optionCompare: null,
    optionValue: null,
    refGroup: 7,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 1,
    referenceData: [
      {
        id: 409,
        externalId: '86',
        name: 'MetroNet FE',
        externalCode: 'MTN',
        refGroup: '7',
      },
      {
        id: 410,
        externalId: '87',
        name: 'MetroNet GE',
        externalCode: 'MTN',
        refGroup: '7',
      },
      {
        id: 411,
        externalId: '88',
        name: 'MetroNet 2FE',
        externalCode: 'MTN',
        refGroup: '7',
      },
      {
        id: 412,
        externalId: '172',
        name: 'Hội nghị truyền hình',
        externalCode: 'MTN',
        refGroup: '7',
      },
      {
        id: 413,
        externalId: '233',
        name: 'MetroNet 10GE',
        externalCode: 'MTN',
        refGroup: '7',
      },
      {
        id: 414,
        externalId: '244',
        name: 'Metronet_POP',
        externalCode: 'MTN',
        refGroup: '7',
      },
      {
        id: 415,
        externalId: '245',
        name: 'Metronet_NNI',
        externalCode: 'MTN',
        refGroup: '7',
      },
    ],
  },
  {
    id: 12,
    name: 'Kênh thuê riêng (điểm-điểm)',
    behaviorType: 2,
    behaviorName: 'Nhu cầu dịch vụ mới',
    groupCode: null,
    groupName: null,
    optionProperty: 'TSL',
    optionType: 3,
    optionCompare: null,
    optionValue: null,
    refGroup: 9,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 1,
    referenceData: [
      {
        id: 448,
        externalId: '93',
        name: 'Leasedline V35',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 449,
        externalId: '162',
        name: 'Leasedline 34M (16E1)',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 450,
        externalId: '163',
        name: 'Leasedline 10GE',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 451,
        externalId: '164',
        name: 'Leasedline STM4',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 452,
        externalId: '165',
        name: 'Leasedline STM16',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 453,
        externalId: '166',
        name: 'Leasedline Gpon',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 454,
        externalId: '22',
        name: 'Leasedline FE',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 455,
        externalId: '29',
        name: 'Đôi cáp đồng',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 456,
        externalId: '33',
        name: 'Đôi cáp quang',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 457,
        externalId: '66',
        name: 'Leasedline GE',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 458,
        externalId: '67',
        name: 'Leasedline E1',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 459,
        externalId: '68',
        name: 'Leasedline STM1',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 460,
        externalId: '69',
        name: 'Leasedline nx64k',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 461,
        externalId: '71',
        name: 'Nail up',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 462,
        externalId: '72',
        name: 'Trực thông đồng',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 463,
        externalId: '73',
        name: 'Trực thông quang',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 464,
        externalId: '94',
        name: 'Leasedline V35',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 465,
        externalId: '95',
        name: 'TSL SHDSL',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 466,
        externalId: '123',
        name: 'Cáp quang trắng',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 467,
        externalId: '239',
        name: 'Metronet FE',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 468,
        externalId: '240',
        name: 'Metronet GE',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 469,
        externalId: '241',
        name: 'Metronet 10GE',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 470,
        externalId: '242',
        name: 'Megawan quang FE',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 471,
        externalId: '243',
        name: 'Megawan quang GE',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 472,
        externalId: '248',
        name: 'Leasedline E1 POP',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 473,
        externalId: '249',
        name: 'Leasedline FE POP',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 474,
        externalId: '250',
        name: 'Leasedline GE POP',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 475,
        externalId: '251',
        name: 'Leasedline Gpon POP',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 476,
        externalId: '252',
        name: 'Leasedline STM1 POP',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 477,
        externalId: '253',
        name: 'Leasedline STM16 POP',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 478,
        externalId: '254',
        name: 'Leasedline STM4 POP',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 479,
        externalId: '255',
        name: 'Leasedline V35 POP',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 480,
        externalId: '256',
        name: 'Leasedline nx64k POP',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 481,
        externalId: '257',
        name: 'Kênh quá giang',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 482,
        externalId: '258',
        name: 'Kênh dung lượng',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 483,
        externalId: '265',
        name: 'Leasedline T3 POP',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 484,
        externalId: '273',
        name: 'Leasedline POP',
        externalCode: 'TSL',
        refGroup: '9',
      },
      {
        id: 485,
        externalId: '320',
        name: 'Kênh ngoài lãnh thổ',
        externalCode: 'TSL',
        refGroup: '9',
      },
    ],
  },
  {
    id: 13,
    name: 'Gphone',
    behaviorType: 2,
    behaviorName: 'Nhu cầu dịch vụ mới',
    groupCode: null,
    groupName: null,
    optionProperty: 'Gphone',
    optionType: 3,
    optionCompare: null,
    optionValue: null,
    refGroup: 10,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 1,
    referenceData: [
      {
        id: 486,
        externalId: '32',
        name: 'Gphone trả sau',
        externalCode: 'GPHONE',
        refGroup: '10',
      },
      {
        id: 487,
        externalId: '34',
        name: 'Gphone trả trước',
        externalCode: 'GPHONE',
        refGroup: '10',
      },
    ],
  },
  {
    id: 20,
    name: 'Phí phụ thu',
    behaviorType: 2,
    behaviorName: 'Nhu cầu dịch vụ mới',
    groupCode: null,
    groupName: null,
    optionProperty: 'PHI_PHUTHU',
    optionType: 3,
    optionCompare: null,
    optionValue: null,
    refGroup: 18,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 1,
    referenceData: [
      {
        id: 717,
        externalId: '51',
        name: 'Phí phụ thu',
        externalCode: 'PHI_PHUTHU',
        refGroup: '18',
      },
    ],
  },
  {
    id: 26,
    name: 'TSL đối tác',
    behaviorType: 2,
    behaviorName: 'Nhu cầu dịch vụ mới',
    groupCode: null,
    groupName: null,
    optionProperty: 'TSL_DT',
    optionType: 3,
    optionCompare: null,
    optionValue: null,
    refGroup: 24,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 1,
    referenceData: [
      {
        id: 724,
        externalId: '232',
        name: 'TSL đối tác',
        externalCode: 'TSL_DT',
        refGroup: '24',
      },
    ],
  },
  {
    id: 23,
    name: 'IMS đối tác',
    behaviorType: 2,
    behaviorName: 'Nhu cầu dịch vụ mới',
    groupCode: null,
    groupName: null,
    optionProperty: 'IMS_DT',
    optionType: 3,
    optionCompare: null,
    optionValue: null,
    refGroup: 21,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 1,
    referenceData: [
      {
        id: 720,
        externalId: '228',
        name: 'IMS đối tác',
        externalCode: 'IMS_DT',
        refGroup: '21',
      },
    ],
  },
  {
    id: 18,
    name: 'Dịch vụ CNTT',
    behaviorType: 2,
    behaviorName: 'Nhu cầu dịch vụ mới',
    groupCode: null,
    groupName: null,
    optionProperty: 'CNTT',
    optionType: 3,
    optionCompare: null,
    optionValue: null,
    refGroup: 15,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 1,
    referenceData: [
      {
        id: 536,
        externalId: '348',
        name: 'VNPT EMR',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 537,
        externalId: '349',
        name: 'VNPT iSee',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 538,
        externalId: '351',
        name: 'Chuyển vùng quốc tế',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 539,
        externalId: '352',
        name: 'vnEdu Connect',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 540,
        externalId: '353',
        name: 'Bảo hiểm hỗ trợ viện phí',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 541,
        externalId: '354',
        name: 'Bảo hiểm tai nạn',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 542,
        externalId: '355',
        name: 'Bảo hiểm học sinh, sinh viên',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 543,
        externalId: '356',
        name: 'Bảo hiểm nhà',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 544,
        externalId: '357',
        name: 'Bảo hiểm TNDS xe cơ giới',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 545,
        externalId: '358',
        name: 'Voice Brandname',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 546,
        externalId: '359',
        name: 'Thoại quốc tế',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 547,
        externalId: '360',
        name: 'VNPT ICS',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 548,
        externalId: '361',
        name: 'Microsoft 1',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 549,
        externalId: '362',
        name: 'Microsoft 2',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 550,
        externalId: '363',
        name: 'Microsoft 3',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 551,
        externalId: '364',
        name: 'Microsoft 4',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 552,
        externalId: '365',
        name: 'Microsoft 5',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 553,
        externalId: '366',
        name: 'Adobe',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 554,
        externalId: '367',
        name: 'Kaspersky',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 555,
        externalId: '2114',
        name: 'Báo hiệu quốc tế',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 556,
        externalId: '2115',
        name: 'One Bussiness triển khai On-Premise',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 557,
        externalId: '369',
        name: 'VNPT SCC',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 558,
        externalId: '221',
        name: 'VNEdu FAS',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 559,
        externalId: '223',
        name: 'VNPT Smart Tourist',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 560,
        externalId: '225',
        name: 'vnEdu - Portal',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 561,
        externalId: '227',
        name: 'VNEdu eLession',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 562,
        externalId: '234',
        name: 'VNPT-eDoc',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 563,
        externalId: '235',
        name: 'VNPT VXP',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 564,
        externalId: '236',
        name: 'Phần mềm SALESPRO',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 565,
        externalId: '261',
        name: 'VNPT LIS',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 566,
        externalId: '262',
        name: 'Phần mềm hợp tác',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 567,
        externalId: '263',
        name: 'VNPT RIS/PACS',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 568,
        externalId: '264',
        name: 'VNPT VSR (LRIS)',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 569,
        externalId: '267',
        name: 'VNPT MCAP',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 570,
        externalId: '268',
        name: 'VNPT SMCC',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 571,
        externalId: '269',
        name: 'Quản lý công chứng',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 572,
        externalId: '270',
        name: 'IT CARE',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 573,
        externalId: '272',
        name: 'Moblie Money',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 574,
        externalId: '277',
        name: 'VNPT AsMe',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 575,
        externalId: '278',
        name: 'VNPT-iDVC',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 576,
        externalId: '280',
        name: 'eZoZo',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 577,
        externalId: '281',
        name: 'SME-HRM: Quản lý nhân sự',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 578,
        externalId: '282',
        name: 'SME-SALES: Quản lý bán hàng',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 579,
        externalId: '283',
        name: 'SME-WEBSITE: Dịch vụ thiết kế Website',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 580,
        externalId: '284',
        name: 'vnFace',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 581,
        externalId: '285',
        name: 'VNPT AI Camera',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 582,
        externalId: '286',
        name: 'VNPT BMIS',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 583,
        externalId: '287',
        name: 'VNPT eDIG',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 584,
        externalId: '290',
        name: 'VNPT eContract',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 585,
        externalId: '291',
        name: 'vnEdu HSS',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 586,
        externalId: '292',
        name: 'VNPT one Business',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 587,
        externalId: '294',
        name: 'POSIO',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 588,
        externalId: '295',
        name: 'VNPT Holio',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 589,
        externalId: '296',
        name: 'VNPT Home 1',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 590,
        externalId: '299',
        name: 'VNCARE',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 591,
        externalId: '300',
        name: 'Bảo hiểm số kèm fiber',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 592,
        externalId: '301',
        name: 'Phần mềm tự phát triển',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 593,
        externalId: '302',
        name: 'VNPT HKD',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 594,
        externalId: '303',
        name: 'VNPT IQMS',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 595,
        externalId: '304',
        name: 'Nhắn tin P2P',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 596,
        externalId: '307',
        name: 'VNPT LMS ETEP',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 597,
        externalId: '308',
        name: 'SD Wan',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 598,
        externalId: '309',
        name: 'VNPT HSSK',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 599,
        externalId: '316',
        name: 'Nhắn tin A2P',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 600,
        externalId: '317',
        name: 'VNPT IOC',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 601,
        externalId: '319',
        name: 'VNPT eTicket',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 602,
        externalId: '321',
        name: 'vnEdu Mobile App',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 603,
        externalId: '322',
        name: 'VNPT GoMeet',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 604,
        externalId: '323',
        name: 'vnEdu Content',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 605,
        externalId: '326',
        name: 'VNPT iLIS',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 606,
        externalId: '327',
        name: 'VNPT ODP',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 607,
        externalId: '328',
        name: 'Giải pháp tổng đài dịch vụ công 1022',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 608,
        externalId: '329',
        name: 'VNPT Ehc',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 609,
        externalId: '330',
        name: 'VNPT IOT Platform',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 610,
        externalId: '331',
        name: 'VNPT ASXH',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 611,
        externalId: '332',
        name: 'VNPT MIS',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 612,
        externalId: '337',
        name: 'VNPT ORIM-X',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 613,
        externalId: '338',
        name: 'vnSocial',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 614,
        externalId: '339',
        name: 'VNPT IDP',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 615,
        externalId: '340',
        name: 'VNPT EOC',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 616,
        externalId: '341',
        name: 'VNPT-CONG-DLYT',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 617,
        externalId: '342',
        name: 'Cơ sở dữ liệu quốc gia dân cư',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 618,
        externalId: '344',
        name: 'Phần mềm phổ cập giáo dục',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 619,
        externalId: '345',
        name: 'VNPT ERP',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 620,
        externalId: '346',
        name: 'Sàn nông sản',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 621,
        externalId: '347',
        name: 'vFarm',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 622,
        externalId: '2116',
        name: 'Hóa đơn điện tử - Máy tính tiền',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 623,
        externalId: '2117',
        name: 'VNPT Cloud Contact Center',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 624,
        externalId: '370',
        name: 'VNedu Học bạ điện tử',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 625,
        externalId: '371',
        name: 'HP Wifi',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 626,
        externalId: '2118',
        name: 'VNPT Cloud Contact Center',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 627,
        externalId: '372',
        name: 'VNPT ID CHECK',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 628,
        externalId: '373',
        name: 'VNPT Invoice Inbot',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 629,
        externalId: '374',
        name: 'VNPT SmartCloud VPC',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 630,
        externalId: '375',
        name: 'VNPT CLOUD PACS',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 631,
        externalId: '237',
        name: 'vnPortal',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 632,
        externalId: '35',
        name: 'VNPT iOffice',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 633,
        externalId: '38',
        name: '1800',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 634,
        externalId: '52',
        name: 'VNPT Check',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 635,
        externalId: '53',
        name: 'VNPT Kios',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 636,
        externalId: '54',
        name: 'VNPT Pos',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 637,
        externalId: '56',
        name: 'VNPT Smart Ads',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 638,
        externalId: '80',
        name: 'VNPT CA Plugin',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 639,
        externalId: '118',
        name: 'vnEdu',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 640,
        externalId: '120',
        name: 'VNPT Portal',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 641,
        externalId: '121',
        name: 'VNPT iGate',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 642,
        externalId: '122',
        name: 'VNPT Invoice',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 643,
        externalId: '127',
        name: '1900',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 644,
        externalId: '131',
        name: 'SMS Brandname',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 645,
        externalId: '136',
        name: 'VNPT HIS',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 646,
        externalId: '140',
        name: 'VNPT CA Sign Server',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 647,
        externalId: '141',
        name: 'Wifi Marketing',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 648,
        externalId: '142',
        name: 'Vpoint',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 649,
        externalId: '143',
        name: 'VNPT DMS',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 650,
        externalId: '145',
        name: 'VNPT Karo',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 651,
        externalId: '147',
        name: 'Tên miền Việt Nam',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 652,
        externalId: '148',
        name: 'Tên miền Quốc tế',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 653,
        externalId: '149',
        name: 'VCC',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 654,
        externalId: '151',
        name: 'Thiết kế web',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 655,
        externalId: '156',
        name: 'VNPT HMIS',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 656,
        externalId: '160',
        name: 'VNPT ORM',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 657,
        externalId: '161',
        name: 'VNPT Pharmacy',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 658,
        externalId: '167',
        name: 'VietLot',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 659,
        externalId: '168',
        name: 'My English',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 660,
        externalId: '175',
        name: 'VNPT eReceipt',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 661,
        externalId: '176',
        name: 'VNPT CCVC',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 662,
        externalId: '177',
        name: 'VNPT HRM',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 663,
        externalId: '178',
        name: 'VNPT BSC',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 664,
        externalId: '179',
        name: 'VNPT SmartEdu',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 665,
        externalId: '180',
        name: 'VNEdu SmartID',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 666,
        externalId: '182',
        name: 'Số ngôi sao',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 667,
        externalId: '200',
        name: 'VNPT eCabinet',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 668,
        externalId: '202',
        name: 'VNPT HCSN',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 669,
        externalId: '203',
        name: 'VNEdu IOC',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 670,
        externalId: '204',
        name: 'VNEdu Enrollment',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 671,
        externalId: '205',
        name: 'VNPT LIB',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 672,
        externalId: '206',
        name: 'Quảng cáo doanh nghiệp',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 673,
        externalId: '207',
        name: 'Thu âm Tổng đài',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 674,
        externalId: '208',
        name: 'VNPT E-Learning',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 675,
        externalId: '209',
        name: 'Tư vấn du lịch',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 676,
        externalId: '211',
        name: 'VNEdu TKB',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 677,
        externalId: '212',
        name: 'VNEdu NMS',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 678,
        externalId: '213',
        name: 'VNEdu FMS',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 679,
        externalId: '214',
        name: 'VNEdu COC',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 680,
        externalId: '215',
        name: 'VNEdu SLL',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 681,
        externalId: '216',
        name: 'VNEdu QoE',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 682,
        externalId: '217',
        name: 'VNEdu eLessionTool',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 683,
        externalId: '218',
        name: 'VNEdu Preschool',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 684,
        externalId: '219',
        name: 'VNEdu eCert',
        externalCode: 'CNTT',
        refGroup: '15',
      },
      {
        id: 685,
        externalId: '220',
        name: 'VNEdu-Quiz',
        externalCode: 'CNTT',
        refGroup: '15',
      },
    ],
  },
  {
    id: 21,
    name: 'Hạ tầng viễn thông',
    behaviorType: 2,
    behaviorName: 'Nhu cầu dịch vụ mới',
    groupCode: null,
    groupName: null,
    optionProperty: 'HTVT',
    optionType: 3,
    optionCompare: null,
    optionValue: null,
    refGroup: 19,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 1,
    referenceData: [
      {
        id: 718,
        externalId: '158',
        name: 'Hạ tầng viễn thông',
        externalCode: 'HTVT',
        refGroup: '19',
      },
    ],
  },
  {
    id: 22,
    name: 'Gói đa dịch vụ',
    behaviorType: 2,
    behaviorName: 'Nhu cầu dịch vụ mới',
    groupCode: null,
    groupName: null,
    optionProperty: 'GOI_DADV',
    optionType: 3,
    optionCompare: null,
    optionValue: null,
    refGroup: 20,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 1,
    referenceData: [
      {
        id: 719,
        externalId: '170',
        name: 'Gói đa dịch vụ',
        externalCode: 'GOI_DADV',
        refGroup: '20',
      },
    ],
  },
  {
    id: 19,
    name: 'Trung tâm dữ liệu',
    behaviorType: 2,
    behaviorName: 'Nhu cầu dịch vụ mới',
    groupCode: null,
    groupName: null,
    optionProperty: 'TTDL',
    optionType: 3,
    optionCompare: null,
    optionValue: null,
    refGroup: 16,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 1,
    referenceData: [
      {
        id: 686,
        externalId: '9',
        name: 'VNPT Email SMD',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 687,
        externalId: '12',
        name: 'Web Hosting',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 688,
        externalId: '39',
        name: 'VNPT Colocation',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 689,
        externalId: '40',
        name: 'Premium Cloud',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 690,
        externalId: '41',
        name: 'FTP',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 691,
        externalId: '42',
        name: 'Mail Plus',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 692,
        externalId: '43',
        name: 'VNPT Email Secure',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 693,
        externalId: '44',
        name: 'VNPT Email Quốc tế',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 694,
        externalId: '45',
        name: 'Fmail SERVER',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 695,
        externalId: '46',
        name: 'Vnmail',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 696,
        externalId: '47',
        name: '8x83',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 697,
        externalId: '48',
        name: 'PRM taxi',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 698,
        externalId: '50',
        name: 'Mail VNN',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 699,
        externalId: '110',
        name: 'Telehosting',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 700,
        externalId: '111',
        name: 'VNPT VPS',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 701,
        externalId: '112',
        name: 'VNPT CDN',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 702,
        externalId: '124',
        name: 'Mail Offline',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 703,
        externalId: '139',
        name: 'VNPT Dedicated Server',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 704,
        externalId: '144',
        name: 'VNPT Tracking',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 705,
        externalId: '150',
        name: 'Fmail',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 706,
        externalId: '152',
        name: 'My Cloud',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 707,
        externalId: '153',
        name: 'VNPT SmartCloud',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 708,
        externalId: '155',
        name: 'Dịch vụ 6x65, 8x88',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 709,
        externalId: '159',
        name: 'Mail Hosting',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 710,
        externalId: '173',
        name: 'Tổng đài ảo 3CX',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 711,
        externalId: '174',
        name: 'VNPT OLAP',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 712,
        externalId: '183',
        name: 'Mail Enterprise',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 713,
        externalId: '184',
        name: 'Contact Center',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 714,
        externalId: '310',
        name: 'VNPT MAIL Solutions',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 715,
        externalId: '343',
        name: 'VNPT iStorage',
        externalCode: 'TTDL',
        refGroup: '16',
      },
      {
        id: 716,
        externalId: '368',
        name: 'Đặt máy chủ PMVT',
        externalCode: 'TTDL',
        refGroup: '16',
      },
    ],
  },
  {
    id: 24,
    name: 'BRCĐ đối tác',
    behaviorType: 2,
    behaviorName: 'Nhu cầu dịch vụ mới',
    groupCode: null,
    groupName: null,
    optionProperty: 'BRCD_DT',
    optionType: 3,
    optionCompare: null,
    optionValue: null,
    refGroup: 22,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 1,
    referenceData: [
      {
        id: 721,
        externalId: '229',
        name: 'Fiber đối tác',
        externalCode: 'BRCD_DT',
        refGroup: '22',
      },
      {
        id: 722,
        externalId: '230',
        name: 'Truyền hình IP đối tác',
        externalCode: 'BRCD_DT',
        refGroup: '22',
      },
    ],
  },
  {
    id: 25,
    name: 'Megawan đối tác',
    behaviorType: 2,
    behaviorName: 'Nhu cầu dịch vụ mới',
    groupCode: null,
    groupName: null,
    optionProperty: 'MGW_DT',
    optionType: 3,
    optionCompare: null,
    optionValue: null,
    refGroup: 23,
    criteriaType: null,
    type: 'event',
    status: 1,
    customerType: 1,
    referenceData: [
      {
        id: 723,
        externalId: '231',
        name: 'MGW đối tác',
        externalCode: 'MGW_DT',
        refGroup: '23',
      },
    ],
  },
];
