export const RESET_STATE = 'TIEM_NANG_RESET_STATE';

export const FIND_CUSTOMER = 'FIND_CUSTOMER';
export const GET_LIST_CITY = 'GET_LIST_CITY';
export const GET_LIST_DISTRICT = 'GET_LIST_DISTRICT';
export const GET_LIST_WARD = 'GET_LIST_WARD';
export const GET_LIST_AREA = 'GET_LIST_AREA';

export const REQUEST_LOADING = 'TIEM_NANG_REQUEST_LOADING';
export const REQUEST_FAILED = 'TIEM_NANG_REQUEST_FAILED';
