export const RESET_STATE = 'KHO_KH_RESET_STATE';

export const LIST_CRITERIA_NEW_CUSTOMER = 'KHO_KH_LIST_CRITERIA_NEW_CUSTOMER';

export const REQUEST_LOADING = 'KHO_KH_REQUEST_LOADING';
export const REQUEST_FAILED = 'KHO_KH_REQUEST_FAILED';
